# Generated by Django 5.1.6 on 2025-04-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='no data'),
            preserve_default=False,
        ),
    ]
