# Generated by Django 5.1.6 on 2025-03-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='no data', upload_to='article/'),
            preserve_default=False,
        ),
    ]
